<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mc</string>
	</array>
	<key>keyEquivalent</key>
	<string>~@m</string>
	<key>name</key>
	<string>MC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#link</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ruby</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sql</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#erb</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#javascript</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#raw</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\w(.*):$\n?</string>
			<key>name</key>
			<string>entity.name.function.mc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^:(.*):$\n?</string>
			<key>name</key>
			<string>meta.diff.header.mc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*[^\*]*\*</string>
			<key>name</key>
			<string>emphasized.mc</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>erb</key>
		<dict>
			<key>begin</key>
			<string>```erb|```html</string>
			<key>end</key>
			<string>```</string>
			<key>name</key>
			<string>source.erb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.ruby</string>
				</dict>
			</array>
		</dict>
		<key>javascript</key>
		<dict>
			<key>begin</key>
			<string>```javascript</string>
			<key>end</key>
			<string>```</string>
			<key>name</key>
			<string>source.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>link</key>
		<dict>
			<key>match</key>
			<string>(https?|ftp|mailto):\S+?(?=[)&gt;,.':;"]*(\s|$)|$)</string>
			<key>name</key>
			<string>string.mc</string>
		</dict>
		<key>raw</key>
		<dict>
			<key>begin</key>
			<string>```raw</string>
			<key>end</key>
			<string>```</string>
			<key>name</key>
			<string>markup.raw.inline.mc</string>
		</dict>
		<key>ruby</key>
		<dict>
			<key>begin</key>
			<string>```ruby</string>
			<key>end</key>
			<string>```</string>
			<key>name</key>
			<string>source.ruby</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>sql</key>
		<dict>
			<key>begin</key>
			<string>```sql</string>
			<key>end</key>
			<string>```</string>
			<key>name</key>
			<string>source.sql</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.plain.mc</string>
	<key>uuid</key>
	<string>95D13267-348B-4E3B-8D63-9BC26430C02B</string>
</dict>
</plist>
